version: "3.9"

services:
  api-docenti:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "production"
      PORT: "3000"    # Next.js usa SEMPRE la 3000 se non hai cambiato il server
    ports:
      - "3002:3000"
    volumes:
      - api-docenti:/app/data
    restart: unless-stopped

volumes:
  api-docenti:
