version: "3.9"

services:
  api-docenti:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "production"
      PORT: "3002"
    ports:
      - "3002:3002"
    volumes:
      - api-docenti:/app/data
    restart: unless-stopped

volumes:
  api-docenti:
